[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=D:\workspace\Token-Game\outputs\TokenGameLauncher.exe
FriendlyName=Token Game
AppLaunched=start-game.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
FILE0="start-game.bat"
FILE1="index.cjs"
[SourceFiles]
SourceFiles0=D:\workspace\Token-Game\launcher\
SourceFiles1=D:\workspace\Token-Game\apps\server\dist\
[SourceFiles0]
%FILE0%=
[SourceFiles1]
%FILE1%=
